import mongoose, { Schema, model, type HydratedDocument, type Model } from 'mongoose';

/**
 * A door-scanner pass: one shareable /scan/<token> link for one gate helper.
 * The FIRST device that opens the link claims it (deviceId) — after that the
 * token refuses every other device, so a forwarded link is useless. Organizers
 * can mint several per event and revoke them individually.
 */
export type ScannerPassDocument = {
  eventId: mongoose.Types.ObjectId;
  createdBy: mongoose.Types.ObjectId;
  /** SCN-… secret in the link. */
  token: string;
  /** Organizer-facing label, e.g. "Gate A helper". */
  label: string;
  /** Random id generated by the claiming device ('' = not claimed yet). */
  deviceId: string;
  claimedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

const scannerPassSchema = new Schema<ScannerPassDocument>(
  {
    eventId: { type: Schema.Types.ObjectId, ref: 'Event', required: true, index: true },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    token: { type: String, required: true, unique: true, index: true },
    label: { type: String, default: '', maxlength: 60 },
    deviceId: { type: String, default: '' },
    claimedAt: { type: Date, default: null },
  },
  { timestamps: true, versionKey: false },
);

export type ScannerPass = HydratedDocument<ScannerPassDocument>;
type ScannerPassModelType = Model<ScannerPassDocument>;

export const ScannerPassModel =
  (mongoose.models.ScannerPass as ScannerPassModelType) ?? model<ScannerPassDocument>('ScannerPass', scannerPassSchema);
