export const config = {
  port: Number(process.env.PORT ?? 3001),
  mongoUri: process.env.MONGODB_URI ?? 'mongodb://127.0.0.1:27017/guildos',
  corsOrigin: process.env.CORS_ORIGIN ?? 'http://localhost:3000',
  jwtSecret: process.env.JWT_SECRET ?? 'dev-secret-change-me',
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI,
  frontendUrl: process.env.FRONTEND_URL ?? 'http://localhost:3000',
  emailFrom: process.env.EMAIL_FROM ?? 'GuildOS <no-reply@guildos.local>',
  smtpHost: process.env.SMTP_HOST,
  smtpPort: Number(process.env.SMTP_PORT ?? 587),
  smtpUser: process.env.SMTP_USER,
  smtpPass: process.env.SMTP_PASS,
  accessTokenTtlMs: 1000 * 60 * 15,
  refreshTokenTtlMs: 1000 * 60 * 60 * 24 * 30,
  verificationTokenTtlMs: 1000 * 60 * 60 * 24,
  resetTokenTtlMs: 1000 * 60 * 30,
  cookieDomain: process.env.COOKIE_DOMAIN,
  openAiApiKey: process.env.OPENAI_API_KEY,
  openAiModel: process.env.OPENAI_MODEL ?? 'gpt-4o-mini',
  eventReminderIntervalMs: Number(process.env.EVENT_REMINDER_INTERVAL_MS ?? 1000 * 60 * 15),
  eventReminderWindowMs: Number(process.env.EVENT_REMINDER_WINDOW_MS ?? 1000 * 60 * 60 * 24),
  eventFinalizeIntervalMs: Number(process.env.EVENT_FINALIZE_INTERVAL_MS ?? 1000 * 60 * 30),
  eventFinalizeGraceMs: Number(process.env.EVENT_FINALIZE_GRACE_MS ?? 1000 * 60 * 30),
  opportunitySyncIntervalMs: Number(process.env.OPPORTUNITY_SYNC_INTERVAL_MS ?? 1000 * 60 * 60 * 6),
  opportunitySyncEnabled: process.env.OPPORTUNITY_SYNC_ENABLED === 'true',
  adzunaAppId: process.env.ADZUNA_APP_ID,
  adzunaAppKey: process.env.ADZUNA_APP_KEY,
  adzunaCountry: process.env.ADZUNA_COUNTRY ?? 'gb',
  joobleApiKey: process.env.JOOBLE_API_KEY,
  joobleKeywords: process.env.JOOBLE_KEYWORDS ?? 'internship',
  joobleLocation: process.env.JOOBLE_LOCATION ?? '',
  opportunityRssFeeds: (process.env.OPPORTUNITY_RSS_FEEDS ?? '')
    .split(',')
    .map((u) => u.trim())
    .filter(Boolean),
  isProduction: process.env.NODE_ENV === 'production',
  rateLimitWindowMs: 1000 * 60,
  rateLimitMax: 40,
  adminEmail: process.env.ADMIN_EMAIL,
  adminPassword: process.env.ADMIN_PASSWORD,
  adminName: process.env.ADMIN_NAME ?? 'GuildOS Admin',
};
