'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

import { verifyCv, type CvVerification } from '../../../../components/guildos/cv-api';
import { CvDocumentView } from '../../../../components/guildos/cv/cv-document-view';

export default function CvVerifyPage() {
  const params = useParams<{ verificationId: string }>();
  const verificationId = typeof params?.verificationId === 'string' ? params.verificationId : '';
  const [cv, setCv] = useState<CvVerification | null>(null);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!verificationId) return;
    let cancelled = false;
    void (async () => {
      try {
        const result = await verifyCv(verificationId);
        if (!cancelled) setCv(result.cv);
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : 'CV not found');
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [verificationId]);

  if (error) {
    return (
      <main className="mx-auto max-w-3xl px-4 py-10">
        <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
      </main>
    );
  }

  if (!cv) {
    return <main className="mx-auto max-w-3xl px-4 py-10"><p className="text-slate-500">Verifying CV…</p></main>;
  }

  return (
    <main className="mx-auto max-w-4xl space-y-6 px-4 py-10">
      <div className="no-print rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">
        <p><span className="font-semibold">Authentic · Verified</span> — this CV was generated by GuildOS from {cv.ownerName}&apos;s verified records.</p>
      </div>

      <div className="no-print grid gap-4 sm:grid-cols-4">
        <Stat label="Owner" value={cv.ownerName} />
        <Stat label="Generated" value={new Date(cv.generatedAt).toLocaleDateString()} />
        <Stat label="Certificates" value={cv.certificateCount} />
        <Stat label="Leadership roles" value={cv.leadershipCount} />
      </div>

      <div className="overflow-hidden rounded-2xl border border-slate-200 shadow-sm">
        <CvDocumentView
          content={cv.content}
          template={cv.template}
          cvId={cv.cvId}
          verificationId={cv.verificationId}
        />
      </div>

      <p className="no-print text-center text-xs text-slate-400">
        Verification ID {cv.verificationId} · <a href={cv.profileUrl} className="underline">View public profile</a>
      </p>
    </main>
  );
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4">
      <p className="truncate text-lg font-semibold text-slate-900">{value}</p>
      <p className="text-xs text-slate-500">{label}</p>
    </div>
  );
}
