'use client';

import { useState } from 'react';
import { generateEventDraft, type EventDraft } from '../event-api';
import { Button } from '../ui/button';
import { Section } from './event-form-ui';

export function AiEventAssistant({ onApply }: { onApply: (draft: EventDraft) => void }) {
  const [prompt, setPrompt] = useState('');
  const [draft, setDraft] = useState<EventDraft | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  async function handleGenerate() {
    if (!prompt.trim()) return;
    try {
      setBusy(true);
      setError('');
      const result = await generateEventDraft(prompt);
      setDraft(result.draft);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unable to generate draft');
    } finally {
      setBusy(false);
    }
  }

  return (
    <Section title="AI Event Assistant">
      <p className="text-sm text-slate-500">Describe your event in a sentence and generate a starting draft you can edit.</p>
      <textarea
        className="ev-input min-h-20"
        placeholder="e.g. We want to teach first-year students Git and GitHub."
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
      />
      <div className="flex flex-wrap items-center gap-3">
        <Button variant="secondary" onClick={() => void handleGenerate()} disabled={busy || !prompt.trim()}>
          {busy ? 'Generating…' : 'Generate Draft'}
        </Button>
        {error ? <span className="text-sm text-red-600">{error}</span> : null}
      </div>

      {draft ? (
        <div className="mt-2 space-y-3 rounded-2xl border border-slate-200 bg-slate-50 p-4">
          <div>
            <p className="text-xs uppercase tracking-wide text-slate-400">Title</p>
            <p className="font-medium text-slate-900">{draft.title}</p>
          </div>
          <div>
            <p className="text-xs uppercase tracking-wide text-slate-400">Description</p>
            <p className="text-sm text-slate-700">{draft.description}</p>
          </div>
          {draft.agenda?.length ? (
            <div>
              <p className="text-xs uppercase tracking-wide text-slate-400">Agenda</p>
              <ul className="list-disc pl-5 text-sm text-slate-700">
                {draft.agenda.map((item, i) => <li key={i}>{item}</li>)}
              </ul>
            </div>
          ) : null}
          {draft.audience ? (
            <div>
              <p className="text-xs uppercase tracking-wide text-slate-400">Audience</p>
              <p className="text-sm text-slate-700">{draft.audience}</p>
            </div>
          ) : null}
          <div className="flex items-center gap-3">
            <Button variant="primary" onClick={() => onApply(draft)}>Apply to form</Button>
            <span className="text-xs text-slate-400">{draft.source === 'ai' ? 'Generated by AI' : 'Template draft'}</span>
          </div>
        </div>
      ) : null}
    </Section>
  );
}
